export const responsive = {
    superLargeDesktop: {
      // the naming can be any, depends on you.
      breakpoint: { max: 4000, min: 1024 },
      items: 6,
      slidesToSlide: 2,
    },
    desktop: {
      breakpoint: { max: 1024, min: 800 },
      items: 4,
    },
    tablet: {
      breakpoint: { max: 800, min: 464 },
      items: 2,
    },
    mobile: {
      breakpoint: { max: 464, min: 0 },
      items: 1,
    },
  };


export const youAlsoLikeData = [
  {
    id: 6,
    imageurl: "http://magento2.magentech.com/themes/sm_shopping/pub/media/catalog/product/cache/e9bcb962a9408957578e6af2c852a0c4/e/l/elec-16_2.jpg",
    name: "HP Elite Computer C2D 3.0 New 4GB",
    price: "50.00",
    discount: -13,
    discountPrice: "9.60",
    description: "Some text about the product..",
  },
  {
    id: 4,
    imageurl: "https://i.ibb.co/wMnK2Yj/4.jpg",
    name: "The Wonder and Science of Sound",
    price: "50.00",
    discount: -15,
    discountPrice: "59.00",
    description: "Some text about the product..",
  },
  {
    id: 1,
    imageurl: "https://i.ibb.co/g4DGFYP/1.jpg",
    name: "Panasonic In-Ear Stereo Earphones",
    price: "68.00",
    discountPrice: "72.00",
    discount: -6,
    description: "Some text about the product..",
  },
  {
    id: 2,
    imageurl: "https://i.ibb.co/RTtY90n/2.jpg",
    name: "Nikon D3300 AF-P DX 18-55mm Digital SLR",
    price: "80.00",
    discountPrice: "83.00",
    discount: -6,
    description: "Some text about the product..",
  },
  {
    id: 5,
    imageurl: "https://i.ibb.co/P47QRXK/5.jpg",
    name: "Ricoh Theta 360 Spherical Camera",
    price: "4.50",
    discount: -4,
    discountPrice: "4.70",
    description: "Some text about the product..",
  },
  {
    id: 3,
    imageurl: "https://i.ibb.co/8mgg8Kv/3.jpg",
    name: "HD Tablet with Alexa Hands Free",
    price: "75.00",
    discount: -7,
    discountPrice: "75.00",
    description: "Some text about the product..",
  },
  {
    id: 7,
    imageurl: "http://magento2.magentech.com/themes/sm_shopping/pub/media/catalog/product/cache/e9bcb962a9408957578e6af2c852a0c4/e/l/elec-19_1.jpg",
    name: "Tascam Closed Black Headphone Text..",
    price: "50.00",
    discount: -13,
    discountPrice: "9.60",
    description: "Some text about the product..",
  },
  {
    id: 8,
    imageurl: "http://magento2.magentech.com/themes/sm_shopping/pub/media/catalog/product/cache/e9bcb962a9408957578e6af2c852a0c4/0/1/01.jpg",
    name: "Sony W800S 20.1 MP Di Camera for long",
    price: "50.00",
    discount: -13,
    discountPrice: "9.60",
    description: "Some text about the product..",
  },
  {
    id: 6,
    imageurl: "http://magento2.magentech.com/themes/sm_shopping/pub/media/catalog/product/cache/e9bcb962a9408957578e6af2c852a0c4/e/l/elec-16_2.jpg",
    name: "HP Elite Computer C2D 3.0 New 4GB",
    price: "50.00",
    discount: -13,
    discountPrice: "9.60",
    description: "Some text about the product..",
  },
];
