export const bestSellerData = [
    {
        title: "Apple MacBook Pro",
        desc: "Powerful laptop for professionals with Retina display and M1 Pro chip. The MacBook Pro delivers exceptional performance, stunning visuals, and advanced features for creative and professional users.",
        price: 1999.99,
        rating: 4.9,
        discount: 10,
        image: "https://i.ibb.co/1Kd6b41/apple-macbook-pro.png",
    },
    {
        title: "Samsung Galaxy S21",
        desc: "Flagship smartphone with a stunning display, powerful camera, and 5G capability. The Samsung Galaxy S21 sets the standard for mobile innovation, offering a premium experience for users who demand the best.",
        price: 899.99,
        rating: 4.7,
        discount: 5,
        image: "https://i.ibb.co/FDkXVY3/samsung-galaxy-s21.png",
    },
    {
        title: "Sony WH-1000XM4 Wireless Noise-Canceling Headphones",
        desc: "Premium over-ear headphones with industry-leading noise cancellation technology. The Sony WH-1000XM4 headphones provide an immersive listening experience, perfect for music enthusiasts and frequent travelers.",
        price: 349.99,
        rating: 4.8,
        discount: 15,
        image: "https://i.ibb.co/g3L3LHj/sony-wh1000xm4.png",
    },
    {
        title: "Fitbit Charge 5",
        desc: "Advanced fitness tracker with built-in GPS, heart rate monitoring, and EDA sensor. The Fitbit Charge 5 helps you achieve your fitness goals with precision tracking, a sleek design, and advanced health features.",
        price: 179.99,
        rating: 4.5,
        discount: 0,
        image: "https://i.ibb.co/gZYXMD5/fitbit-charge-5.png",
    },
    {
        title: "Dell XPS 13",
        desc: "Ultra-thin and lightweight laptop with a borderless InfinityEdge display. The Dell XPS 13 combines style and performance, making it the perfect choice for professionals on the go.",
        price: 1199.99,
        rating: 4.6,
        discount: 8,
        image: "https://i.ibb.co/Zf8nQXp/dell-xps-13.png",
    },
    {
        title: "Bose QuietComfort Earbuds",
        desc: "Wireless earbuds with active noise cancellation and impressive sound quality. The Bose QuietComfort Earbuds deliver premium audio and a comfortable fit, ideal for users who demand the best in sound technology.",
        price: 279.99,
        rating: 4.7,
        discount: 0,
        image: "https://i.ibb.co/dJhktsW/bose-quietcomfort-earbuds.png",
    },
    {
        title: "OnePlus 9 Pro",
        desc: "High-performance smartphone with Hasselblad camera and fast charging. The OnePlus 9 Pro redefines mobile photography and performance, offering a flagship experience for tech enthusiasts.",
        price: 999.99,
        rating: 4.6,
        discount: 12,
        image: "https://i.ibb.co/yRXVqvL/oneplus-9-pro.png",
    },
    {
        title: "Nintendo Switch",
        desc: "Versatile gaming console for at-home and on-the-go gaming experiences. The Nintendo Switch provides a unique gaming experience, seamlessly transitioning between home and handheld modes for gaming enthusiasts of all ages.",
        price: 299.99,
        rating: 4.8,
        discount: 0,
        image: "https://i.ibb.co/Jjnf4Jv/nintendo-switch.png",
    },
];